/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Token
         * @description Exchange a username and password for an access/refresh pair.
         *
         *     The access token is returned in the body *and* set as an ``HttpOnly`` cookie. Both, not either:
         *     the body is what a ``fetch`` client attaches as ``Authorization: Bearer`` and what a test or a
         *     ``curl`` uses, while the cookie is the only way an ``EventSource`` can authenticate at all.
         *
         *     The response also says who the caller is and whether they are an ops lead, so the frontend
         *     renders the priority-override control from what the API told it rather than from decoding a
         *     token it has no business parsing.
         *
         *     Errors: ``401 invalid_credentials`` (unknown username, wrong password, inactive account — one
         *     answer for all three, so this route cannot enumerate accounts), ``422 validation_error``.
         */
        post: operations["apps_accounts_api_routers_post_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Token Refresh
         * @description Renew an access token from a refresh token, and re-set the cookie with it.
         *
         *     ``auth=None`` on purpose: the whole point of this route is to be reachable with an access token
         *     that has already expired. The refresh token in the body is the credential.
         *
         *     The account is re-read here, not trusted from the token's claims, so deactivating somebody takes
         *     effect within one access-token lifetime rather than within the refresh window.
         *
         *     Errors: ``401 invalid_token`` (malformed, expired, not a refresh token, or an account that can
         *     no longer sign in), ``422 validation_error``.
         */
        post: operations["apps_accounts_api_routers_post_token_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Logout
         * @description Clear the access cookie.
         *
         *     Authenticated like every other route, which is not ceremony: an unauthenticated endpoint that
         *     deletes a cookie is a cross-origin nuisance that logs people out. It is also idempotent —
         *     clearing a cookie that is not there is a 204 — so a client retrying after a dropped response
         *     gets the same answer.
         *
         *     **The tokens themselves are not revoked**, and that is written down rather than hidden. There is
         *     no blacklist table (see :mod:`apps.accounts.services.sign_in`). What this removes is the copy
         *     the browser sends automatically; the client drops the pair it holds in memory, and the access
         *     token expires on its own within minutes. Server-side revocation would need a durable blacklist
         *     and a reason to run it, and this product has neither yet.
         */
        post: operations["apps_accounts_api_routers_post_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Return every active taxonomy value the frontend renders a picker from.
         *
         *     Engagement types, project types, stages, priorities, roles and currencies, each list in the
         *     order an operator arranged it.
         *
         *     Unauthenticated like every other read, and deliberately one document: a form needs all six
         *     lists before it can draw itself, and six requests to draw one form is six chances to render
         *     half a page.
         *
         *     Currencies carry ``minor_units`` beside ``code`` and ``label``. It is the only field a client
         *     cannot derive — 28000 CLP is $28.000 and 28000 USD is $280.00 — so a frontend that formatted
         *     with a hardcoded 2 would be wrong by two orders of magnitude for every zero-decimal currency.
         *
         *     Workflow states are **not** here: a state is scoped to its workflow and the legal moves out of
         *     one are ``transitions`` on the project detail (`docs/API.md` §2.2). A global state list would
         *     invite the client to guess legality, which is exactly what that field exists to prevent.
         */
        get: operations["apps_catalog_api_routers_get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description The prioritized project queue: score, breakdown and risk flags, in one read.
         *
         *     Served from ``ProjectSnapshot`` — the whole command center in one index scan rather than a
         *     six-table join with per-row aggregates (ARCHITECTURE §8). The flags and the health beside each
         *     row are evaluated from that row at request time (ADR 0011), so the queue is correct the moment
         *     it is loaded rather than the moment it was last rebuilt.
         */
        get: operations["apps_portfolio_api_routers_get_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description One project with its tasks, blockers, risk flags and **legal transitions**.
         *
         *     ``transitions`` is the only source of transition buttons: the frontend renders exactly what
         *     arrives and never guesses legality, so adding a workflow state is a fixture row.
         */
        get: operations["apps_portfolio_api_routers_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Project
         * @description Edit a project's mutable fields. Absent means untouched; explicit ``null`` clears.
         *
         *     ``workflow_state``, ``health`` and ``score`` are not fields of this payload at all: a state
         *     moves through the transition route, and the other two are derived.
         */
        patch: operations["apps_portfolio_api_routers_patch_project"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Project
         * @description Register a project in the initial state of the workflow its engagement type binds to.
         *
         *     Neither ``code`` nor ``workflow_state`` is accepted: the first is allocated by the service, the
         *     second is resolved from ``WorkflowBinding`` (CLAUDE.md rule 2).
         */
        post: operations["apps_portfolio_api_routers_post_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Project Transition
         * @description Move a project along a declared edge, returning it with its **new** legal transitions.
         *
         *     An undeclared or inactive edge is ``409 transition_not_allowed`` carrying the moves that *are*
         *     legal, so a client whose button list went stale resyncs from the rejection.
         */
        post: operations["apps_portfolio_api_routers_post_project_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Load
         * @description Load per person, computed from task rows at read time.
         *
         *     The source ``Team`` sheet's counters are a stale projection of the same rows and are
         *     deliberately not imported: a stored count and the tasks it summarises drift apart in silence.
         */
        get: operations["apps_portfolio_api_routers_get_team_load"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Tasks
         * @description One page of a project's tasks, ordered for triage unless the caller says otherwise.
         *
         *     Default order is severity descending then soonest due — the order an operator actually works
         *     in. ``priority`` sorts by ``Priority.weight``, so a priority inserted above ``critica`` from
         *     the admin sorts correctly with no code change.
         */
        get: operations["apps_work_api_routers_get_project_tasks"];
        put?: never;
        /**
         * Post Project Task
         * @description Add a task to a project, in the initial state of the task workflow.
         *
         *     A dependency that would close a loop in the project's graph is refused before any edge is
         *     written, so a rejected cycle leaves no task with half its prerequisites.
         */
        post: operations["apps_work_api_routers_post_project_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_code}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Task Transition
         * @description Move a task along a declared edge of the task workflow.
         *
         *     A task entering or leaving a ``BLOCKED``-category state changes its project's derived health,
         *     and nothing has to be written for that to be true: health is computed when the project is read
         *     (ADR 0011). What the ``task.state_changed`` event does cause is a rescore and a read-model
         *     rebuild, downstream and asynchronously. None of that happens here: a slow rescore must not be
         *     able to roll back a legitimate move.
         */
        post: operations["apps_work_api_routers_post_task_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Project Blocker
         * @description Raise an impediment against a project, or against one task of it.
         *
         *     Raising a blocker does not change any workflow state. Blocking the work and recording why it is
         *     blocked are two facts, and collapsing them would make "unblock" ambiguous.
         */
        post: operations["apps_work_api_routers_post_project_blocker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockers/{blocker_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Blocker Resolve
         * @description Close an open blocker, stating how it was cleared.
         *
         *     Resolving an already-resolved blocker is ``409 conflicting_state`` with
         *     ``details.current = "resolved"``, checked under a row lock — so it is a genuine second
         *     resolution rather than a lost update overwriting the first resolver's reason.
         *
         *     A project whose last open blocker is cleared loses the ``BLOCKED`` risk flag on the next
         *     snapshot rebuild. The API does not change the workflow state as a side effect.
         */
        post: operations["apps_work_api_routers_post_blocker_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Project Note
         * @description Append a chronological comment to a project, or to one task of it.
         */
        post: operations["apps_work_api_routers_post_project_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Activity
         * @description The project's timeline, newest first.
         *
         *     ``metadata.origin`` distinguishes ``MANUAL`` from ``POLICY`` on every ``PRIORITY_CHANGED`` row,
         *     which is how a reader tells a human's decision from the engine's recomputation. Records sharing
         *     a ``correlation_id`` are one decision and the UI groups them.
         *
         *     A project code matching nothing returns an empty page rather than a 404: the trail is keyed by
         *     business code and outlives the row it describes, so "no records" is the honest answer even for
         *     a project that no longer exists.
         */
        get: operations["apps_activity_api_routers_get_project_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/priority-override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Priority Override
         * @description Force a project's position in the queue, on the record.
         *
         *     The computed ``score.value`` is returned unchanged: the override is stored separately, so the
         *     ranking stays auditable and reversible and the UI can show both numbers. Emits a
         *     ``PRIORITY_CHANGED`` record with ``metadata.origin = "MANUAL"``, correlated with the records of
         *     anything the move displaced.
         *
         *     **Ops lead only** (``403 permission_denied`` otherwise). This is the one place a person
         *     overrules the ranking engine for the whole board, and a queue anybody can reorder is not a
         *     prioritized queue.
         */
        post: operations["apps_prioritization_api_routers_post_priority_override"];
        /**
         * Delete Priority Override
         * @description Lift the override, restoring the engine's ranking with no recomputation.
         *
         *     Idempotent: revoking when nothing is in force writes no record and emits no event, so a client
         *     retrying after a dropped response gets the same 204 and the timeline does not grow a second
         *     entry for one revert. The override row is revoked, never deleted — it is the evidence that
         *     somebody forced a rank and why.
         *
         *     **Ops lead only** (``403 permission_denied`` otherwise), for symmetry with applying one: a rank
         *     that one person may force and anybody may lift is not a decision, it is a suggestion.
         */
        delete: operations["apps_prioritization_api_routers_delete_priority_override"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_code}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Project Recompute
         * @description Rebuild one project's score and risk flags now, instead of waiting for an event.
         *
         *     The automatic path is unaffected and remains the normal one: a data change publishes an event
         *     and the ``priority-recalculator`` reacts, while a clock tick covers the time-derived signals.
         *     This route exists for the two moments nothing will arrive — a policy version was just activated,
         *     or an operator distrusts a row — and it is deliberately a ``POST``: it writes.
         *
         *     It emits no event. Broadcasting ``project.priority.recalculated`` for a rebuild that reproduces
         *     the number already stored would tell every open dashboard that something happened when nothing
         *     did; the response carries ``changed`` so the caller knows either way.
         */
        post: operations["apps_prioritization_api_routers_post_project_recompute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Portfolio Recompute
         * @description Rebuild the whole active portfolio against the active policy, at one instant.
         *
         *     A separate route rather than the same one with an optional project, because "rescore everything"
         *     and "rescore this" have different blast radii and a client should have to say which it meant
         *     (CLAUDE.md rule 13). Every project is scored for the same ``ran_at``, so two projects with the
         *     same facts cannot end up ranked apart by how long the loop took.
         *
         *     Archived projects are skipped: they are out of the queue by definition.
         *
         *     **Ops lead only** (``403 permission_denied`` otherwise). Not because rescoring is dangerous —
         *     it writes derived numbers and emits nothing — but because it is portfolio-wide and expensive,
         *     and a route any member can hammer against every project is a denial-of-service surface with a
         *     friendly name. The single-project route beside it stays open to every member.
         */
        post: operations["apps_prioritization_api_routers_post_portfolio_recompute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Liveness
         * @description Answer that this process is running. Checks nothing, on purpose.
         *
         *     A dependency check here would make a Redis or PostgreSQL outage restart the API, which does not
         *     repair either one and removes the last process able to answer at all. Liveness is about the
         *     process; readiness is about the request.
         */
        get: operations["config_health_get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Readiness
         * @description Report whether this instance can serve a request, with per-check detail when it cannot.
         *
         *     Every check runs even after one has failed. Short-circuiting would save a round trip and cost
         *     the operator the second half of the picture — "the database is down" and "the database and
         *     Redis are both down" call for different responses.
         *
         *     Returns 503 with the same body shape as the 200, so one parser covers both.
         */
        get: operations["config_health_get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Health
         * @description Report the outbox backlog, the dead-letter count and the age of the last clock tick.
         *
         *     **Always 200, including when every number is alarming.** This route exists to be read by a
         *     human or scraped by a dashboard, never to gate a container healthcheck: a poisoned event must
         *     not be able to restart the API.
         */
        get: operations["config_health_get_pipeline_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorRef
         * @description One person, as every payload that names a person renders them.
         *
         *     ``alias`` is ``accounts.User.code`` — the stable slug the API accepts back as input — and
         *     ``label`` is ``accounts.User.alias``, the display name. The two names are inverted with
         *     respect to the model's columns because that is what `docs/API.md` §1.6 fixed on the wire, and
         *     the wire is the contract the frontend is generated from.
         */
        ActorRef: {
            /** Alias */
            alias: string;
            /** Label */
            label: string;
            /** Role */
            role?: string | null;
        };
        /**
         * TokenPair
         * @description An access token, its refresh token, and who they belong to.
         *
         *     Returned only by sign-in. The refresh token is *not* set as a cookie: it is the long-lived
         *     credential, it is never needed by ``EventSource``, and putting it in the browser's automatic
         *     request path would extend the blast radius of the one attack the access cookie's short lifetime
         *     is there to bound.
         */
        TokenPair: {
            /** Access */
            access: string;
            /** Expires In */
            expires_in: number;
            actor: components["schemas"]["ActorRef"];
            /** Is Ops Lead */
            is_ops_lead: boolean;
            /** Refresh */
            refresh: string;
        };
        /**
         * CredentialsIn
         * @description Body of ``POST /api/v1/auth/token``.
         *
         *     ``min_length=1`` on both, so an empty string is a 422 naming the field rather than a 401 that
         *     tells the operator their password is wrong when they simply did not type one.
         */
        CredentialsIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * AccessGrant
         * @description One access token and everything the client needs to use it.
         *
         *     ``expires_in`` is seconds, not an absolute instant, so a client with a skewed clock still
         *     schedules its refresh correctly.
         */
        AccessGrant: {
            /** Access */
            access: string;
            /** Expires In */
            expires_in: number;
            actor: components["schemas"]["ActorRef"];
            /** Is Ops Lead */
            is_ops_lead: boolean;
        };
        /**
         * RefreshIn
         * @description Body of ``POST /api/v1/auth/token/refresh``.
         *
         *     The refresh token travels in the body and never as a cookie: it is the long-lived credential,
         *     ``EventSource`` has no use for it, and keeping it out of the browser's automatic request path is
         *     what bounds the damage the short-lived access cookie can do.
         */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /**
         * CatalogView
         * @description Every taxonomy the frontend renders a picker for, in one response.
         *
         *     One document rather than six endpoints because the client needs all of them before it can draw
         *     a single form, and six round trips to draw one form is six chances to render half a page. Each
         *     list holds only the active rows, in the operator's own ``order``: a retired value keeps
         *     resolving on the projects that already point at it, but must not appear in a picker where
         *     somebody could choose it again.
         *
         *     An empty list is a legitimate answer — a taxonomy nobody has seeded yet — and the client
         *     renders an empty select rather than treating it as a failure.
         */
        CatalogView: {
            /**
             * Engagement Types
             * @default []
             */
            engagement_types: components["schemas"]["TaxonomyRef"][];
            /**
             * Project Types
             * @default []
             */
            project_types: components["schemas"]["TaxonomyRef"][];
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["TaxonomyRef"][];
            /**
             * Priorities
             * @default []
             */
            priorities: components["schemas"]["TaxonomyRef"][];
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["TaxonomyRef"][];
            /**
             * Currencies
             * @default []
             */
            currencies: components["schemas"]["CurrencyRef"][];
        };
        /**
         * CurrencyRef
         * @description One currency, ready to render *and* to format an amount with.
         *
         *     ``TaxonomyRef`` plus the one fact a client cannot derive: how many decimal places the amount
         *     carries. Extending the shared reference rather than defining a parallel one keeps a currency
         *     renderable by the same chip component as every other taxonomy — a client that only wants
         *     ``{code, label, color}`` reads exactly those and ignores the rest.
         *
         *     Attributes:
         *         minor_units: ISO-4217 exponent — 0 for CLP and JPY, 2 for USD and EUR. Formatting 28000
         *             without it is wrong by two orders of magnitude for a zero-decimal currency.
         */
        CurrencyRef: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Color */
            color?: string | null;
            /** Minor Units */
            minor_units: number;
        };
        /**
         * TaxonomyRef
         * @description One operator-editable catalog value, ready to render.
         *
         *     ``color`` is ``None`` rather than ``""`` when the operator set none: absence is a signal the
         *     client must be able to see, so it can fall back to its own neutral token instead of painting a
         *     swatch of transparent black.
         */
        TaxonomyRef: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Color */
            color?: string | null;
        };
        /**
         * QueueQuery
         * @description Query parameters of ``GET /api/v1/queue``.
         *
         *     Repeatable facets arrive as lists and OR their values, which is what a multi-select means.
         *     ``risk_flag`` is the exception and ANDs: "blocked **and** overdue" is the question an operator
         *     asks, and the OR of two common flags is most of the portfolio.
         *
         *     An unknown value is not an error — it simply matches nothing — but an unparseable one is a 422,
         *     and so is an ``order_by`` outside the allowlist (`docs/API.md` §1.4).
         */
        QueueQuery: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Owner */
            owner?: string[];
            /** Engagement Type */
            engagement_type?: string[];
            /** Risk Flag */
            risk_flag?: string[];
            /** Project Type */
            project_type?: string | null;
            /** Stage */
            stage?: string | null;
            /** State */
            state?: string | null;
            /** State Category */
            state_category?: string | null;
            /** Health */
            health?: ("HEALTHY" | "AT_RISK" | "BLOCKED") | null;
            /** Has Open Blockers */
            has_open_blockers?: boolean | null;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /**
             * Q
             * @default
             */
            q: string;
            /**
             * Order By
             * @default -score
             */
            order_by: string;
        };
        /**
         * HealthRef
         * @description Derived project health, ready to render.
         *
         *     Structural rather than operator data: a pure function of the open risk flags, so the client
         *     branches on ``code`` and renders ``label``. It is never writable — `docs/API.md` §2.4 rejects
         *     an attempt to set it — because a health somebody typed would immediately disagree with the
         *     flags it is supposed to summarise.
         */
        HealthRef: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** Page[QueueItemView] */
        Page_QueueItemView_: {
            /** Items */
            items: components["schemas"]["QueueItemView"][];
            /** Count */
            count: number;
        };
        /**
         * QueueItemView
         * @description One row of the prioritized queue, read from ``ProjectSnapshot`` alone.
         *
         *     ``score.value`` is the computed number and is never rewritten by ``override``: when
         *     ``override`` is present the UI labels the row as manually forced and still shows what the
         *     engine thought (ARCHITECTURE §4.2). A client that renders one instead of the other destroys
         *     the only evidence that somebody argued with the ranking.
         *
         *     Absent values are ``null`` and mean absent — a missing ``target_date`` is the
         *     ``NO_TARGET_DATE`` signal itself, and substituting today's date would erase a real risk.
         *
         *     ``project_type`` and ``stage`` travel as bare codes rather than as
         *     :class:`~apps.shared.refs.TaxonomyRef`, because the read model denormalizes a label only for
         *     the fields the queue actually renders as text. The project detail carries the full references.
         */
        QueueItemView: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Client Alias */
            client_alias: string;
            owner?: components["schemas"]["ActorRef"] | null;
            engagement_type: components["schemas"]["TaxonomyRef"];
            /** Project Type Code */
            project_type_code?: string | null;
            /** Stage Code */
            stage_code?: string | null;
            state: components["schemas"]["StateRef"];
            health: components["schemas"]["HealthRef"];
            /** Target Date */
            target_date?: string | null;
            /** Business Value */
            business_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Next Step */
            next_step?: string | null;
            /**
             * Open Tasks
             * @default 0
             */
            open_tasks: number;
            /**
             * Overdue Tasks
             * @default 0
             */
            overdue_tasks: number;
            /**
             * Blocked Tasks
             * @default 0
             */
            blocked_tasks: number;
            /**
             * Open Blockers
             * @default 0
             */
            open_blockers: number;
            score: components["schemas"]["ScoreView"];
            override?: components["schemas"]["QueueOverrideView"] | null;
            /**
             * Risk Flags
             * @default []
             */
            risk_flags: components["schemas"]["RiskFlagView"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * QueueOverrideView
         * @description The fact that a queue row was manually forced, as the read model records it.
         *
         *     Narrower than :class:`~apps.prioritization.domain.views.OverrideView` on purpose. The snapshot
         *     denormalizes the position and the reason — what the row has to *show* — and not the actor or
         *     the timestamps, which belong to the audit and are served with the project detail. Widening it
         *     would mean widening the read model to satisfy a list view that already fits in one index scan.
         */
        QueueOverrideView: {
            /** Position */
            position?: number | null;
            /** Reason */
            reason: string;
        };
        /**
         * RiskFlagView
         * @description One raised risk, as the panels and the row indicators render it.
         *
         *     ``code`` is deliberately an open set (`docs/API.md` §4.2): adding a specification adds a code
         *     (CLAUDE.md rule 8), so a client that does not recognise one renders it with its ``reason``
         *     rather than dropping it — a dropped flag is a risk nobody sees.
         */
        RiskFlagView: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * ScoreSignalView
         * @description One line of the argument: what the signal read, what it was worth, and why.
         *
         *     ``contribution`` is ``raw * weight * 100`` as it was computed, not as the client should
         *     recompute it — floating point in a browser would put a row a hundredth of a point out of order
         *     against a server that used ``Decimal``.
         */
        ScoreSignalView: {
            /** Code */
            code: string;
            /** Raw */
            raw: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Reason */
            reason: string;
        };
        /**
         * ScoreView
         * @description A project's computed rank, with the whole document that defends it.
         *
         *     ``value`` is the computed 0-100 number and is **never** rewritten by an override: an override
         *     is stored beside it, so the queue can label a row as manually forced while still showing what
         *     the engine thought (ARCHITECTURE §4.2). A client that overwrites one with the other destroys
         *     the only signal that says the ranking was argued with.
         *
         *     ``breakdown`` arrives sorted by ``contribution`` descending — the order the UI reads it in —
         *     and that ordering is the writer's, preserved here rather than re-sorted, so a policy that ever
         *     emits ties keeps a stable presentation.
         */
        ScoreView: {
            /** Value */
            value: number;
            /** Policy Version */
            policy_version: string;
            /** Computed At */
            computed_at?: string | null;
            /**
             * Breakdown
             * @default []
             */
            breakdown: components["schemas"]["ScoreSignalView"][];
            /** Modifiers */
            modifiers?: {
                [key: string]: number;
            };
            /**
             * Flags
             * @default []
             */
            flags: string[];
        };
        /**
         * StateRef
         * @description One workflow state, ready to render and safe to branch on.
         *
         *     ``category`` travels alongside ``code`` because ``code`` is unique only inside its workflow —
         *     two workflows may both own ``bloqueada`` — so a client deciding "is this blocked" reads
         *     ``category`` and never a list of codes it would have to keep in sync (DATA_MODEL §12).
         */
        StateRef: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Category */
            category: string;
            /** Color */
            color?: string | null;
        };
        /**
         * BlockerView
         * @description One impediment, open or cleared.
         *
         *     ``id`` is the numeric primary key and is contract only as a value to hand straight back to
         *     ``POST /api/v1/blockers/{id}/resolve`` (`docs/API.md` §4.2); it is not stable across a reseed.
         *     ``code`` is the business identifier the ``blocker.raised`` envelope carries, and is what a
         *     consumer or an audit reader addresses the row by.
         *
         *     ``resolved_at`` being ``None`` *is* the definition of open — there is no separate boolean,
         *     because two representations of one fact is how the panel and the blockage signal come to
         *     disagree.
         */
        BlockerView: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            owner?: components["schemas"]["ActorRef"] | null;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Resolved At */
            resolved_at?: string | null;
            /**
             * Resolution Reason
             * @default
             */
            resolution_reason: string;
            /**
             * Age Days
             * @default 0
             */
            age_days: number;
            /** Task Code */
            task_code?: string | null;
        };
        /**
         * DependencyRef
         * @description One prerequisite of a task, resolved to a task or kept as the operation's own words.
         *
         *     61 of the 82 source tasks name their dependency as free text that resolves to no task, so an
         *     unresolved reference is the normal case rather than a defect. ``task_code`` is ``None`` then,
         *     and ``raw_label`` still carries what somebody actually wrote — dropping it would delete the
         *     operation's notes in the name of a clean schema.
         */
        DependencyRef: {
            /** Task Code */
            task_code?: string | null;
            /**
             * Raw Label
             * @default
             */
            raw_label: string;
        };
        /**
         * OverrideView
         * @description A human's forced ranking decision, on the record.
         *
         *     ``reason`` is not optional and never empty: it is a database constraint, a service check and a
         *     field here, because a forced position with no recorded justification is indistinguishable from
         *     a bug three weeks later. Exactly one of ``position`` and ``boost`` is set.
         */
        OverrideView: {
            /** Position */
            position?: number | null;
            /** Boost */
            boost?: number | null;
            /** Reason */
            reason: string;
            /** Actor */
            actor: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * ProjectDetailView
         * @description One project in full, read from the write side.
         *
         *     ``transitions`` is the **only** source of transition buttons (`docs/API.md` §2.2). The frontend
         *     holds no list of state codes and never guesses legality, which is what makes adding a workflow
         *     state a fixture row with zero frontend changes. An empty list is a legitimate answer: it means
         *     the project sits in a terminal state, and the UI renders no buttons rather than inventing one.
         *
         *     ``score`` is ``None`` only before the engine has ever run for this project — a freshly created
         *     one, between its ``project.created`` event and the recalculator's first pass. It is not
         *     flattened to zero, because "not scored yet" and "scored zero" rank the same and mean opposite
         *     things.
         */
        ProjectDetailView: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Summary */
            summary?: string | null;
            client: components["schemas"]["TaxonomyRef"];
            owner?: components["schemas"]["ActorRef"] | null;
            engagement_type: components["schemas"]["TaxonomyRef"];
            project_type?: components["schemas"]["TaxonomyRef"] | null;
            stage?: components["schemas"]["TaxonomyRef"] | null;
            state: components["schemas"]["StateRef"];
            health: components["schemas"]["HealthRef"];
            /** Start Date */
            start_date?: string | null;
            /** Target Date */
            target_date?: string | null;
            /** Business Value */
            business_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Next Step */
            next_step?: string | null;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /**
             * Open Tasks
             * @default 0
             */
            open_tasks: number;
            /**
             * Overdue Tasks
             * @default 0
             */
            overdue_tasks: number;
            /**
             * Blocked Tasks
             * @default 0
             */
            blocked_tasks: number;
            /**
             * Open Blockers
             * @default 0
             */
            open_blockers: number;
            score?: components["schemas"]["ScoreView"] | null;
            override?: components["schemas"]["OverrideView"] | null;
            /**
             * Risk Flags
             * @default []
             */
            risk_flags: components["schemas"]["RiskFlagView"][];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskView"][];
            /**
             * Blockers
             * @default []
             */
            blockers: components["schemas"]["BlockerView"][];
            /**
             * Transitions
             * @default []
             */
            transitions: components["schemas"]["TransitionOption"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskView
         * @description One task, as the project detail and the task list render it.
         *
         *     ``state`` carries its ``category`` so the board can group by "blocked" without holding a list
         *     of state codes that two workflows could both own (DATA_MODEL §12).
         */
        TaskView: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            assignee?: components["schemas"]["ActorRef"] | null;
            priority: components["schemas"]["TaxonomyRef"];
            state: components["schemas"]["StateRef"];
            /** Due Date */
            due_date?: string | null;
            /**
             * Is Overdue
             * @default false
             */
            is_overdue: boolean;
            /**
             * Last Progress
             * @default
             */
            last_progress: string;
            /**
             * Dependencies
             * @default []
             */
            dependencies: components["schemas"]["DependencyRef"][];
        };
        /**
         * TransitionOption
         * @description One edge an operator may take from where the aggregate currently sits.
         *
         *     ``requires_reason`` and ``requires_fields`` are shipped rather than enforced client-side only:
         *     the client uses them to ask for the reason *before* the request and to disable a button whose
         *     field is still empty, and the transition service re-checks both, so a client that ignores them
         *     gets a typed 422 instead of a silent move.
         *
         *     ``requires_fields`` names attributes of the aggregate (``next_step``), not of the request body.
         *     An entry that is currently empty on the aggregate means the button renders disabled with the
         *     field named — which is why the list is sent even when it changes nothing about the payload.
         */
        TransitionOption: {
            to_state: components["schemas"]["StateRef"];
            /** Label */
            label: string;
            /**
             * Requires Reason
             * @default false
             */
            requires_reason: boolean;
            /**
             * Requires Fields
             * @default []
             */
            requires_fields: string[];
        };
        /**
         * ProjectUpdateIn
         * @description Body of ``PATCH /api/v1/projects/{code}``.
         *
         *     Every field is optional, and "absent" and "``null``" mean different things: an absent field is
         *     left untouched, an explicitly ``null`` one clears a nullable column. That distinction is the
         *     whole reason this is a schema and not a dict — with a dict, "unset the target date" and "do
         *     not touch the target date" are the same request, and a portfolio quietly loses its deadlines.
         *
         *     The router reads which fields were actually sent from Pydantic's ``model_fields_set`` and
         *     carries that set into the command, so the distinction survives all the way to the service.
         */
        ProjectUpdateIn: {
            /** Name */
            name?: string | null;
            /** Client */
            client?: string | null;
            /** Engagement Type */
            engagement_type?: string | null;
            /** Project Type */
            project_type?: string | null;
            /** Stage */
            stage?: string | null;
            /** Owner */
            owner?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Target Date */
            target_date?: string | null;
            /** Business Value */
            business_value?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Summary */
            summary?: string | null;
            /** Next Step */
            next_step?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /**
         * ProjectCreateIn
         * @description Body of ``POST /api/v1/projects``.
         *
         *     ``code`` is absent by design: the service allocates the next ``PRJ-NN`` inside the creating
         *     transaction. A client that chose its own could collide with a code an already-published event
         *     names, and the event cannot be un-published.
         *
         *     ``workflow_state`` is absent for the same reason it is absent from the update schema: the
         *     project starts in the ``is_initial`` state of the workflow its engagement type binds to, so a
         *     caller cannot enter a project directly into a state no declared transition leads to.
         */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Engagement Type */
            engagement_type: string;
            /** Project Type */
            project_type?: string | null;
            /** Stage */
            stage?: string | null;
            /** Owner */
            owner?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Target Date */
            target_date?: string | null;
            /** Business Value */
            business_value?: number | string | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Next Step
             * @default
             */
            next_step: string;
        };
        /**
         * TransitionIn
         * @description Body of ``POST /api/v1/projects/{code}/transition``.
         *
         *     ``reason`` is optional *here* and mandatory *there*: whether an edge demands one is
         *     ``WorkflowTransition.requires_reason``, a row an operator edits, so making it required in the
         *     schema would freeze a data decision into code. The transition service raises
         *     ``ReasonRequired`` — a typed 422 naming the field — when the edge asks for one and it is blank.
         */
        TransitionIn: {
            /** To State */
            to_state: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * TeamLoadQuery
         * @description Query parameters of ``GET /api/v1/team/load``.
         *
         *     Not paginated: the roster is five people, and a pager over five rows costs the client a second
         *     request to learn there is no second page.
         */
        TeamLoadQuery: {
            /** Owner */
            owner?: string[];
            /**
             * Include Inactive
             * @default false
             */
            include_inactive: boolean;
        };
        /**
         * TeamLoadPage
         * @description The whole roster's load, as ``GET /api/v1/team/load`` returns it.
         *
         *     An ``{items: [...]}`` object rather than a bare array, so the endpoint can grow a sibling key —
         *     a portfolio total, a generated-at instant — without becoming a breaking change for a client
         *     that parsed the top level as a list. It carries no ``count``: this is the whole roster, and a
         *     total beside a complete list is a number that can only ever be redundant or wrong.
         */
        TeamLoadPage: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["TeamLoadView"][];
        };
        /**
         * TeamLoadView
         * @description What one person is carrying right now, computed from task rows at read time.
         *
         *     The source ``Team`` sheet's counters are a stale projection of the same rows and are
         *     deliberately not imported (ARCHITECTURE §10): storing them would let the roster and the work
         *     disagree, and the disagreement would be invisible.
         *
         *     ``is_overloaded`` never lowers a project's score. It raises ``OWNER_OVERLOADED`` on that
         *     person's projects, because being short-staffed is a staffing decision and not a reason for the
         *     work itself to matter less (ARCHITECTURE §4.1).
         */
        TeamLoadView: {
            /** Alias */
            alias: string;
            /** Label */
            label: string;
            /** Role */
            role?: string | null;
            /** Weekly Capacity Points */
            weekly_capacity_points: number;
            /** Load Points */
            load_points: number;
            /** Utilization */
            utilization: number;
            /**
             * Is Overloaded
             * @default false
             */
            is_overloaded: boolean;
            /**
             * Open Tasks
             * @default 0
             */
            open_tasks: number;
            /**
             * Blocked Tasks
             * @default 0
             */
            blocked_tasks: number;
            /**
             * High Or Critical Open
             * @default 0
             */
            high_or_critical_open: number;
            /**
             * Overdue Tasks
             * @default 0
             */
            overdue_tasks: number;
            /**
             * Projects Owned
             * @default 0
             */
            projects_owned: number;
        };
        /**
         * TaskQuery
         * @description Query parameters of ``GET /api/v1/projects/{code}/tasks``.
         *
         *     ``is_overdue`` is a derived facet: it compares ``due_date`` against server time inside the
         *     query, so it can never disagree with the ``is_overdue`` rendered on the rows it returns. The
         *     source spreadsheet's own ``Si``/``No`` column is not imported and is not part of this contract.
         */
        TaskQuery: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Assignee */
            assignee?: string[];
            /** Priority */
            priority?: string[];
            /** State */
            state?: string | null;
            /** State Category */
            state_category?: string | null;
            /** Is Overdue */
            is_overdue?: boolean | null;
            /**
             * Q
             * @default
             */
            q: string;
            /**
             * Order By
             * @default attention
             */
            order_by: string;
        };
        /** Page[TaskView] */
        Page_TaskView_: {
            /** Items */
            items: components["schemas"]["TaskView"][];
            /** Count */
            count: number;
        };
        /**
         * TaskCreateIn
         * @description Body of ``POST /api/v1/projects/{code}/tasks``.
         *
         *     ``depends_on`` names task codes inside the same project. A code that resolves to no task is
         *     kept verbatim as the dependency's ``raw_label`` rather than rejected: 61 of the 82 source tasks
         *     describe their prerequisite in prose, so an unresolvable reference is the normal case and
         *     dropping it would delete the operation's own notes.
         */
        TaskCreateIn: {
            /** Title */
            title: string;
            /** Priority */
            priority: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Assignee */
            assignee?: string | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Last Progress
             * @default
             */
            last_progress: string;
            /** Depends On */
            depends_on?: string[];
        };
        /**
         * TaskTransitionIn
         * @description Body of ``POST /api/v1/tasks/{code}/transition``.
         *
         *     Identical in shape and in error contract to the project transition, against the task workflow.
         *     ``reason`` is optional here and mandatory when the edge sets ``requires_reason`` — a row an
         *     operator edits, so freezing the requirement into the schema would freeze a data decision.
         */
        TaskTransitionIn: {
            /** To State */
            to_state: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * BlockerCreateIn
         * @description Body of ``POST /api/v1/projects/{code}/blockers``.
         *
         *     ``task_code`` attaches the impediment to one task instead of to the project. The project is
         *     recorded either way — the service copies it from the task — so every consumer can resolve a
         *     blocker to a portfolio row without joining through ``Task``.
         */
        BlockerCreateIn: {
            kind: components["schemas"]["BlockerKind"];
            /** Description */
            description: string;
            /** Owner */
            owner?: string | null;
            /** Task Code */
            task_code?: string | null;
        };
        /**
         * BlockerKind
         * @description What sort of impediment a blocker is.
         *
         *     A closed, structural set — unlike a taxonomy in ``catalog``, an operator cannot add a
         *     member without a migration, because the risk and prioritization logic branches on
         *     these values. It lives in ``domain/`` instead of as a ``TextChoices`` on the model so
         *     that service commands can be typed against it without importing Django; ``models.py``
         *     renders it into the field's ``choices``.
         * @enum {string}
         */
        BlockerKind: "EXTERNAL_DEPENDENCY" | "ACCESS" | "DECISION" | "TECHNICAL";
        /**
         * BlockerResolveIn
         * @description Body of ``POST /api/v1/blockers/{id}/resolve``.
         *
         *     ``resolution`` is required and non-empty, here, in the service and as a database check. A
         *     blocker closed without saying how is indistinguishable from one that was never real, and it is
         *     how the same impediment returns a month later with nobody able to say what was tried.
         */
        BlockerResolveIn: {
            /** Resolution */
            resolution: string;
        };
        /**
         * NoteView
         * @description One chronological comment on a project, or on one task of it.
         *
         *     ``author`` is a bare code rather than an :class:`~apps.shared.refs.ActorRef` because the column
         *     is a denormalized string that outlives its author's row and can hold ``system``: resolving it
         *     to a person would fail for exactly the rows the denormalization exists to keep readable.
         *
         *     Nothing parses a note's text. A note is not a substitute for a :class:`BlockerView`, and the
         *     moment something greps it for "blocked" the typed row stops being written.
         */
        NoteView: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Body */
            body: string;
            /** Author */
            author: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Task Code */
            task_code?: string | null;
        };
        /**
         * NoteIn
         * @description Body of ``POST /api/v1/projects/{code}/notes``.
         *
         *     Notes are chronological comments and nothing parses their text. A note is not a substitute for
         *     a :class:`~apps.work.domain.views.BlockerView`: the moment something greps one for "blocked",
         *     the typed row stops being written and the panel stops being true.
         */
        NoteIn: {
            /** Body */
            body: string;
            /** Task Code */
            task_code?: string | null;
        };
        /**
         * TimelineQuery
         * @description Query parameters of ``GET /api/v1/projects/{code}/activity``.
         *
         *     There is no ``order_by``: the timeline is a narrative and is always newest first. An allowlist
         *     with one entry would only advertise a choice that does not exist.
         *
         *     ``verb`` is repeatable and ORs its values. An unrecognised verb is not rejected — the verb set
         *     is closed and versioned by migration, so filtering on one this deployment does not know is a
         *     well-formed question whose answer is "nothing", and a 422 there would break a frontend the
         *     moment a verb is retired.
         *
         *     ``correlation_id`` is the interesting one: records sharing it are **one decision**, so passing
         *     the id from any row expands the whole movement — "A was deprioritized so B could rise" — which
         *     is what makes a reprioritization defensible weeks later.
         */
        TimelineQuery: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Verb */
            verb?: string[];
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
            /** Correlation Id */
            correlation_id?: string | null;
        };
        /**
         * ActivityEntry
         * @description One persisted fact of the audit trail.
         *
         *     It extends the command with the identity the database assigned, so a caller that wrote a
         *     record and a reader that queried one hold the same type. Immutable for the same reason the
         *     table has no ``updated_at``.
         *
         *     Attributes:
         *         id: Primary key of the ``activity_activityrecord`` row.
         */
        ActivityEntry: {
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Verb */
            verb: string;
            /**
             * Origin
             * @default SYSTEM
             */
            origin: string;
            /** Actor */
            actor: string;
            /**
             * From Value
             * @default
             */
            from_value: string;
            /**
             * To Value
             * @default
             */
            to_value: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Correlation Id
             * Format: uuid
             */
            correlation_id: string;
            /** Id */
            id: number;
        };
        JsonValue: unknown;
        /** Page[ActivityEntry] */
        Page_ActivityEntry_: {
            /** Items */
            items: components["schemas"]["ActivityEntry"][];
            /** Count */
            count: number;
        };
        /**
         * OverrideOut
         * @description Response of the override endpoint: the computed score, and the decision beside it.
         *
         *     Both are returned deliberately. ``score.value`` is **unchanged** by the override — the client
         *     labels the row as manually forced and still shows what the engine thought, so a reader can see
         *     the size of the disagreement rather than only its result.
         */
        OverrideOut: {
            /** Code */
            code: string;
            score?: components["schemas"]["ScoreView"] | null;
            override?: components["schemas"]["OverrideView"] | null;
        };
        /**
         * OverrideIn
         * @description Body of ``POST /api/v1/projects/{code}/priority-override``.
         *
         *     ``reason`` is a constraint, not a convention. It is required here, re-checked by the service
         *     and enforced by a database check, because a forced position with no recorded justification is
         *     indistinguishable from a bug three weeks later — and the queue is exactly where nobody would
         *     think to look for one.
         *
         *     Exactly one of ``position`` and ``boost`` must be present. That rule is validated by the
         *     service rather than by this schema so it has a single home: the admin action and any future
         *     importer construct the same command and must be refused for the same reason, with the same
         *     typed error.
         */
        OverrideIn: {
            /** Position */
            position?: number | null;
            /** Boost */
            boost?: number | string | null;
            /** Reason */
            reason: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * Health
         * @description Derived project health.
         *
         *     Never stored on ``Project`` and never edited: it is a function of the open risk flags, so it
         *     cannot disagree with them.
         * @enum {string}
         */
        Health: "HEALTHY" | "AT_RISK" | "BLOCKED";
        /**
         * ProjectRecomputeOut
         * @description One project's line of a rebuild report.
         *
         *     ``changed`` is the interesting field and the reason the report is returned at all: an operator
         *     who forces a recomputation wants to know whether the stored ranking was wrong. A rebuild where
         *     every row reports ``false`` is a healthy system confirming itself, not a wasted call.
         */
        ProjectRecomputeOut: {
            /** Project Code */
            project_code: string;
            /** Value */
            value: number;
            health: components["schemas"]["Health"];
            /** Flags */
            flags: string[];
            /** Changed */
            changed: boolean;
        };
        /**
         * RecomputeOut
         * @description Response of the recompute endpoints.
         *
         *     ``ran_at`` is the single instant every project in ``items`` was scored for. It is reported
         *     rather than left to the client's own clock because it is the answer to "against what time was
         *     this ranking true" — the two time-derived signals make that question load-bearing.
         *
         *     ``changed`` is derived from ``items`` by :meth:`of` and is never assembled independently, so a
         *     body claiming three projects moved while listing none is unrepresentable.
         */
        RecomputeOut: {
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /** Changed */
            changed: number;
            /** Items */
            items: components["schemas"]["ProjectRecomputeOut"][];
        };
        /**
         * LivenessOut
         * @description Response of ``GET /api/v1/health/live``: the process answered, therefore it is alive.
         *
         *     Deliberately carries nothing else. Every field added here is a field somebody eventually
         *     computes, and the first computation that can fail turns liveness into readiness by accident.
         */
        LivenessOut: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * DependencyCheck
         * @description One readiness probe and what it found.
         *
         *     ``detail`` carries the exception's own message on failure, truncated by nothing: it is read by
         *     an operator during an incident, and "connection refused" versus "password authentication
         *     failed" is the difference between restarting a container and fixing a secret.
         */
        DependencyCheck: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * ReadinessOut
         * @description Response of ``GET /api/v1/health/ready``, on both 200 and 503.
         *
         *     The same shape either way, so a probe or a dashboard parses one thing. ``ready`` is the
         *     conjunction of the checks and is not independently settable — a payload where ``ready`` is true
         *     while a check failed is a state this type cannot represent.
         */
        ReadinessOut: {
            /** Ready */
            ready: boolean;
            /** Checks */
            checks: components["schemas"]["DependencyCheck"][];
        };
        /**
         * PipelineOut
         * @description Response of ``GET /api/v1/health/pipeline``: the event pipeline's vital signs.
         *
         *     A thin restatement of :class:`~apps.events.services.PipelineHealth` on purpose. The service's
         *     type is the context's; this one is the wire's, and keeping them separate is what lets the
         *     pipeline read grow a field that the public contract does not have to carry.
         */
        PipelineOut: {
            /** Unpublished */
            unpublished: number;
            /** Oldest Unpublished Age Seconds */
            oldest_unpublished_age_seconds: number | null;
            /** Dead Lettered */
            dead_lettered: number;
            /** Last Tick At */
            last_tick_at: string | null;
            /** Last Tick Age Seconds */
            last_tick_age_seconds: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_accounts_api_routers_post_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    apps_accounts_api_routers_post_token_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrant"];
                };
            };
        };
    };
    apps_accounts_api_routers_post_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_catalog_api_routers_get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogView"];
                };
            };
        };
    };
    apps_portfolio_api_routers_get_queue: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                owner?: string[];
                engagement_type?: string[];
                risk_flag?: string[];
                project_type?: string | null;
                stage?: string | null;
                state?: string | null;
                state_category?: string | null;
                health?: ("HEALTHY" | "AT_RISK" | "BLOCKED") | null;
                has_open_blockers?: boolean | null;
                is_archived?: boolean;
                q?: string;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_QueueItemView_"];
                };
            };
        };
    };
    apps_portfolio_api_routers_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailView"];
                };
            };
        };
    };
    apps_portfolio_api_routers_patch_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailView"];
                };
            };
        };
    };
    apps_portfolio_api_routers_post_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailView"];
                };
            };
        };
    };
    apps_portfolio_api_routers_post_project_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailView"];
                };
            };
        };
    };
    apps_portfolio_api_routers_get_team_load: {
        parameters: {
            query?: {
                owner?: string[];
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLoadPage"];
                };
            };
        };
    };
    apps_work_api_routers_get_project_tasks: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                assignee?: string[];
                priority?: string[];
                state?: string | null;
                state_category?: string | null;
                is_overdue?: boolean | null;
                q?: string;
                order_by?: string;
            };
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TaskView_"];
                };
            };
        };
    };
    apps_work_api_routers_post_project_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
        };
    };
    apps_work_api_routers_post_task_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskTransitionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
        };
    };
    apps_work_api_routers_post_project_blocker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockerCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerView"];
                };
            };
        };
    };
    apps_work_api_routers_post_blocker_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blocker_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockerResolveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerView"];
                };
            };
        };
    };
    apps_work_api_routers_post_project_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteView"];
                };
            };
        };
    };
    apps_activity_api_routers_get_project_activity: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                verb?: string[];
                since?: string | null;
                until?: string | null;
                correlation_id?: string | null;
            };
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActivityEntry_"];
                };
            };
        };
    };
    apps_prioritization_api_routers_post_priority_override: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideOut"];
                };
            };
        };
    };
    apps_prioritization_api_routers_delete_priority_override: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_prioritization_api_routers_post_project_recompute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeOut"];
                };
            };
        };
    };
    apps_prioritization_api_routers_post_portfolio_recompute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeOut"];
                };
            };
        };
    };
    config_health_get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessOut"];
                };
            };
        };
    };
    config_health_get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
        };
    };
    config_health_get_pipeline_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"];
                };
            };
        };
    };
}
