# Generated by Django 6.0.7 on 2026-07-28 20:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("topic", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=16)),
                ("entity_id", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(max_length=32)),
                ("correlation_id", models.UUIDField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("stream_entry_id", models.CharField(blank=True, default="", max_length=32)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "outbox event",
                "verbose_name_plural": "outbox events",
                "db_table": "events_outboxevent",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("published_at__isnull", True)),
                        fields=["occurred_at", "id"],
                        name="events_outbox_unpublished_idx",
                    ),
                    models.Index(fields=["topic", "-occurred_at"], name="events_outbox_topic_idx"),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="events_outbox_entity_idx"
                    ),
                    models.Index(fields=["correlation_id"], name="events_outbox_correlation_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempts__gte", 0)),
                        name="events_outboxevent_attempts_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("published_at__isnull", True),
                            models.Q(("stream_entry_id", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="events_outboxevent_published_has_entry_id",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("consumer_group", models.CharField(max_length=48)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "processed event",
                "verbose_name_plural": "processed events",
                "db_table": "events_processedevent",
                "ordering": ["-processed_at"],
                "indexes": [models.Index(fields=["processed_at"], name="events_processed_at_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "consumer_group"),
                        name="events_processedevent_unique_per_group",
                    )
                ],
            },
        ),
    ]
