# Generated by Django 6.0.7 on 2026-07-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=16, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("weights", models.JSONField()),
                ("modifiers", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "priority policy",
                "verbose_name_plural": "priority policies",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="prioritization_one_active_policy",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriorityOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.SmallIntegerField(blank=True, null=True)),
                (
                    "boost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("reason", models.CharField(max_length=500)),
                ("actor", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_overrides",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "priority override",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["expires_at"], name="prioritization_override_expiry")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("project",),
                        name="prioritization_one_live_override",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("boost__isnull", True), ("position__isnull", False)),
                            models.Q(("boost__isnull", False), ("position__isnull", True)),
                            _connector="OR",
                        ),
                        name="prioritization_override_one_mechanism",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason__regex", "\\S")),
                        name="prioritization_override_reason_present",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriorityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("policy_version", models.CharField(max_length=16)),
                ("breakdown", models.JSONField()),
                ("modifier_total", models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ("computed_at", models.DateTimeField()),
                ("input_hash", models.CharField(blank=True, default="", max_length=64)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_score",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "priority score",
                "ordering": ["-value"],
                "indexes": [
                    models.Index(fields=["-value"], name="prioritization_score_desc"),
                    models.Index(fields=["policy_version"], name="prioritization_score_policy"),
                    models.Index(fields=["valid_until"], name="prioritization_score_valid"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 0), ("value__lte", 100)),
                        name="prioritization_score_within_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=8,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("detected_at", models.DateTimeField()),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_flags",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "risk flag",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("cleared_at__isnull", True)),
                        fields=["project"],
                        name="prioritization_open_flags",
                    ),
                    models.Index(fields=["severity"], name="prioritization_flag_severity"),
                    models.Index(fields=["detected_at"], name="prioritization_flag_detected"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cleared_at__isnull", True)),
                        fields=("project", "code"),
                        name="prioritization_one_open_flag_per_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cleared_at__isnull", True),
                            ("cleared_at__gte", models.F("detected_at")),
                            _connector="OR",
                        ),
                        name="prioritization_flag_cleared_after_detected",
                    ),
                ],
            },
        ),
    ]
