# Generated by Django 6.0.7 on 2026-07-28 20:11

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("workflow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("alias", models.CharField(max_length=96)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ["alias"],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="portfolio_client_code_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "project_code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("project_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("client_alias", models.CharField(max_length=96)),
                ("engagement_type_code", models.CharField(db_index=True, max_length=32)),
                ("engagement_type_label", models.CharField(max_length=64)),
                ("project_type_code", models.CharField(blank=True, default="", max_length=32)),
                ("stage_code", models.CharField(blank=True, default="", max_length=32)),
                ("state_code", models.CharField(max_length=32)),
                ("state_label", models.CharField(max_length=64)),
                ("state_category", models.CharField(db_index=True, max_length=16)),
                (
                    "owner_code",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                ("owner_alias", models.CharField(blank=True, default="", max_length=96)),
                ("owner_load_points", models.SmallIntegerField(default=0)),
                ("owner_capacity_points", models.SmallIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "business_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("next_step", models.CharField(blank=True, default="", max_length=255)),
                ("priority_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "priority_policy_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("breakdown", models.JSONField(default=dict)),
                ("has_override", models.BooleanField(default=False)),
                ("override_position", models.SmallIntegerField(blank=True, null=True)),
                ("override_reason", models.CharField(blank=True, default="", max_length=255)),
                ("risk_flags", models.JSONField(default=list)),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("AT_RISK", "At risk"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="HEALTHY",
                        max_length=16,
                    ),
                ),
                ("open_task_count", models.SmallIntegerField(default=0)),
                ("overdue_task_count", models.SmallIntegerField(default=0)),
                ("blocked_task_count", models.SmallIntegerField(default=0)),
                ("urgent_open_task_count", models.SmallIntegerField(default=0)),
                ("open_blocker_count", models.SmallIntegerField(default=0)),
                ("oldest_blocker_age_days", models.SmallIntegerField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("rebuilt_at", models.DateTimeField(auto_now=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "project snapshot",
                "verbose_name_plural": "project snapshots",
                "ordering": ["-priority_score", "project_code"],
                "indexes": [
                    models.Index(
                        fields=["is_archived", "-priority_score"], name="portfolio_snap_queue"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["risk_flags"], name="portfolio_snap_riskflags_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project_id",), name="portfolio_projectsnapshot_project_id_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=160)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "business_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("summary", models.TextField(blank=True, default="")),
                ("next_step", models.CharField(blank=True, default="", max_length=255)),
                ("is_archived", models.BooleanField(default=False)),
                ("imported_health", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="portfolio.client",
                    ),
                ),
                (
                    "engagement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="catalog.engagementtype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="catalog.projecttype",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="catalog.stage",
                    ),
                ),
                (
                    "workflow_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="workflow.workflowstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["is_archived", "workflow_state"], name="portfolio_prj_arch_state"
                    ),
                    models.Index(fields=["owner", "is_archived"], name="portfolio_prj_owner_arch"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="portfolio_project_code_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_date__isnull", True),
                            ("target_date__isnull", True),
                            ("start_date__lte", models.F("target_date")),
                            _connector="OR",
                        ),
                        name="portfolio_project_dates_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("business_value__isnull", True),
                            ("business_value__gte", 0),
                            _connector="OR",
                        ),
                        name="portfolio_project_business_value_non_negative",
                    ),
                ],
            },
        ),
    ]
