# Generated by Django 6.0.7 on 2026-07-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_add_description"),
        ("workflow", "0002_workflowstate_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="workflow.workflow",
            ),
        ),
    ]
