"""How a test presents a credential.

Imported by every HTTP test in the codebase, which is the point: there is one way to authenticate a
request and it is the same one a client uses. A helper that reached inside ``config.auth`` to fake a
``request.user`` would let the tests keep passing on the day the auth class stops working, and the
one thing these tests exist to prove is that it does.

The password is a per-test literal, not a fixture value and not a setting. ``S106`` is suppressed at
each use with that reason.
"""

from typing import Any

from django.test import Client

from apps.accounts.models import User

#: The password every account built by :func:`make_member` carries. A test double, generated by
#: nobody and shipped nowhere — the seeded accounts get theirs from ``SEED_USER_PASSWORD``.
TEST_PASSWORD = "not-a-real-password"  # noqa: S105

#: Where a client exchanges credentials for a pair. A URL, not a credential, whatever bandit's
#: name-based heuristic makes of the word "token".
TOKEN_URL = "/api/v1/auth/token"  # noqa: S105


def make_member(*, code: str, is_ops_lead: bool = False) -> User:
    """Create one signed-in-capable account.

    Args:
        code: The stable slug, mirrored into ``username`` exactly as the model documents.
        is_ops_lead: Whether the account may override the ranking and rebuild the portfolio. Set
            through ``is_staff``, because that is what :attr:`User.is_ops_lead` reads and a test
            that set some other flag would be testing a rule the API does not apply.

    Returns:
        The saved account, with a usable password.
    """
    user = User.objects.create(
        username=code,
        code=code,
        alias=code.replace(".", " ").title(),
        is_staff=is_ops_lead,
    )
    user.set_password(TEST_PASSWORD)
    user.save(update_fields=["password"])
    return user


def obtain_tokens(client: Client, *, username: str, password: str = TEST_PASSWORD) -> Any:
    """Sign in over HTTP and return the parsed body.

    Deliberately goes through the real route rather than calling ``sign_in`` directly: it is what
    also proves the cookie is set, and it keeps every other test honest about the fact that a token
    is something you obtain, not something you construct.

    Args:
        client: The Django test client, which also keeps the cookie jar.
        username: The account to sign in as.
        password: Its password.

    Returns:
        The decoded ``TokenPair`` body: ``access``, ``refresh``, ``expires_in``, ``actor``,
        ``is_ops_lead``.
    """
    response = client.post(
        TOKEN_URL,
        data={"username": username, "password": password},
        content_type="application/json",
    )
    return response.json()


def bearer(*, username: str, password: str = TEST_PASSWORD) -> dict[str, str]:
    """Sign in and return the header dict every authenticated request in the suite carries.

    Signs in through a *throwaway* client on purpose. Django's test client keeps a cookie jar, so
    signing in through the client under test would leave the access cookie in it and every later
    request would authenticate whether or not the header was attached — which is precisely the
    distinction the cookie tests exist to make.

    Args:
        username: The account to sign in as.
        password: Its password.

    Returns:
        ``{"HTTP_AUTHORIZATION": "Bearer <access token>"}``, ready to splat into a client call.
    """
    tokens = obtain_tokens(Client(), username=username, password=password)
    return {"HTTP_AUTHORIZATION": f"Bearer {tokens['access']}"}
