# Generated by Django 6.0.7 on 2026-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0002_note_task_recent_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
