# Generated by Django 6.0.7 on 2026-07-29 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_currency"),
        ("portfolio", "0004_add_description"),
        ("work", "0003_add_description"),
        ("workflow", "0002_workflowstate_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "is_archived"], name="work_task_project_archived"
            ),
        ),
    ]
