# Generated by Django 6.0.7 on 2026-07-28 20:11

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EngagementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=4),
                ),
            ],
            options={
                "verbose_name": "engagement type",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"], name="catalog_engagementtype_act_ord"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="catalog_engagementtype_code_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight__gt", 0)),
                        name="catalog_engagementtype_weight_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=4),
                ),
                ("is_urgent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "priority",
                "verbose_name_plural": "priorities",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "order"], name="catalog_priority_act_ord")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="catalog_priority_code_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("weight__gt", 0)),
                        name="catalog_priority_weight_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
            ],
            options={
                "verbose_name": "project type",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "order"], name="catalog_projecttype_act_ord")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="catalog_projecttype_code_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
            ],
            options={
                "verbose_name": "role",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "order"], name="catalog_role_act_ord")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="catalog_role_code_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
            ],
            options={
                "verbose_name": "stage",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "order"], name="catalog_stage_act_ord")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="catalog_stage_code_unique")
                ],
            },
        ),
    ]
