# Generated by Django 6.0.7 on 2026-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                ("minor_units", models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "ordering": ("order", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "order"], name="catalog_currency_act_ord")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="catalog_currency_code_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[A-Z]{3}$")),
                        name="catalog_currency_code_is_iso_4217",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minor_units__lte", 4)),
                        name="catalog_currency_minor_units_within_iso_range",
                    ),
                ],
            },
        ),
    ]
