# Generated by Django 6.0.7 on 2026-07-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=96)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("PROJECT", "Project"), ("TASK", "Task")], max_length=8
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["applies_to", "code"],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uniq_workflow_code"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("applies_to",),
                        name="uniq_default_workflow_per_applies_to",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BACKLOG", "Backlog"),
                            ("IN_PROGRESS", "In progress"),
                            ("BLOCKED", "Blocked"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_initial", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("order", models.SmallIntegerField(default=0)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("requires_reason", models.BooleanField(default=False)),
                ("requires_fields", models.JSONField(blank=True, default=list)),
                ("guard", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["from_state", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("PROJECT", "Project"), ("TASK", "Task")], max_length=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "engagement_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_bindings",
                        to="catalog.engagementtype",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["applies_to", "engagement_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("applies_to", "engagement_type"),
                        name="uniq_binding_per_engagement_type",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflowstate",
            index=models.Index(fields=["workflow", "order"], name="idx_state_workflow_order"),
        ),
        migrations.AddIndex(
            model_name="workflowstate",
            index=models.Index(fields=["category"], name="idx_state_category"),
        ),
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                fields=("workflow", "code"), name="uniq_state_code_per_workflow"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True)),
                fields=("workflow",),
                name="uniq_initial_state_per_workflow",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtransition",
            index=models.Index(
                fields=["from_state", "is_active"], name="idx_transition_from_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtransition",
            constraint=models.UniqueConstraint(
                fields=("from_state", "to_state"), name="uniq_transition_state_pair"
            ),
        ),
    ]
