# Generated by Django 6.0.7 on 2026-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
