# Generated by Django 6.0.7 on 2026-07-28 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("project", "Project"), ("task", "Task"), ("blocker", "Blocker")],
                        max_length=16,
                    ),
                ),
                ("entity_id", models.CharField(max_length=32)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STATE_CHANGED", "State changed"),
                            ("PRIORITY_CHANGED", "Priority changed"),
                            ("BLOCKER_RAISED", "Blocker raised"),
                            ("BLOCKER_RESOLVED", "Blocker resolved"),
                            ("OWNER_CHANGED", "Owner changed"),
                            ("NEXT_STEP_SET", "Next step set"),
                            ("TASK_ADDED", "Task added"),
                            ("NOTE_ADDED", "Note added"),
                            ("SEEDED", "Seeded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("POLICY", "Policy"), ("SYSTEM", "System")],
                        default="SYSTEM",
                        max_length=8,
                    ),
                ),
                ("actor", models.CharField(max_length=32)),
                ("from_value", models.CharField(blank=True, default="", max_length=255)),
                ("to_value", models.CharField(blank=True, default="", max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("correlation_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "activity record",
                "verbose_name_plural": "activity records",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-occurred_at"],
                        name="activity_entity_recent_idx",
                    ),
                    models.Index(fields=["correlation_id"], name="activity_correlation_idx"),
                    models.Index(fields=["verb", "-occurred_at"], name="activity_verb_recent_idx"),
                    models.Index(
                        fields=["actor", "-occurred_at"], name="activity_actor_recent_idx"
                    ),
                ],
            },
        ),
    ]
