# Generated by Django 6.0.7 on 2026-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_member_activity_vocabulary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrecord",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("task", "Task"),
                    ("blocker", "Blocker"),
                    ("member", "Member"),
                    ("role", "Role"),
                ],
                max_length=16,
            ),
        ),
    ]
