# Generated by Django 6.0.7 on 2026-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_role_activity_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrecord",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("task", "Task"),
                    ("blocker", "Blocker"),
                    ("member", "Member"),
                    ("role", "Role"),
                    ("workflow", "Workflow"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="activityrecord",
            name="verb",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("STATE_CHANGED", "State changed"),
                    ("PRIORITY_CHANGED", "Priority changed"),
                    ("BLOCKER_RAISED", "Blocker raised"),
                    ("BLOCKER_RESOLVED", "Blocker resolved"),
                    ("OWNER_CHANGED", "Owner changed"),
                    ("NEXT_STEP_SET", "Next step set"),
                    ("TASK_ADDED", "Task added"),
                    ("NOTE_ADDED", "Note added"),
                    ("SEEDED", "Seeded"),
                    ("RENAMED", "Renamed"),
                    ("ROLE_CHANGED", "Role changed"),
                    ("CAPACITY_CHANGED", "Capacity changed"),
                    ("DEACTIVATED", "Deactivated"),
                    ("REACTIVATED", "Reactivated"),
                    ("PASSWORD_RESET", "Password reset"),
                    ("STATE_ADDED", "State added"),
                    ("STATE_EDITED", "State edited"),
                    ("STATE_RETIRED", "State retired"),
                    ("TRANSITION_ADDED", "Transition added"),
                    ("TRANSITION_EDITED", "Transition edited"),
                    ("TRANSITION_RETIRED", "Transition retired"),
                ],
                max_length=24,
            ),
        ),
    ]
