# Generated by Django 6.0.7 on 2026-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0007_add_workflow_assigned_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrecord",
            name="verb",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("STATE_CHANGED", "State changed"),
                    ("PRIORITY_CHANGED", "Priority changed"),
                    ("BLOCKER_RAISED", "Blocker raised"),
                    ("BLOCKER_RESOLVED", "Blocker resolved"),
                    ("OWNER_CHANGED", "Owner changed"),
                    ("NEXT_STEP_SET", "Next step set"),
                    ("TASK_ADDED", "Task added"),
                    ("TASK_REMOVED", "Task removed"),
                    ("TASK_RESTORED", "Task restored"),
                    ("DEPENDENCIES_CHANGED", "Dependencies changed"),
                    ("NOTE_ADDED", "Note added"),
                    ("SEEDED", "Seeded"),
                    ("RENAMED", "Renamed"),
                    ("ROLE_CHANGED", "Role changed"),
                    ("CAPACITY_CHANGED", "Capacity changed"),
                    ("DEACTIVATED", "Deactivated"),
                    ("REACTIVATED", "Reactivated"),
                    ("PASSWORD_RESET", "Password reset"),
                    ("STATE_ADDED", "State added"),
                    ("STATE_EDITED", "State edited"),
                    ("STATE_RETIRED", "State retired"),
                    ("TRANSITION_ADDED", "Transition added"),
                    ("TRANSITION_EDITED", "Transition edited"),
                    ("TRANSITION_RETIRED", "Transition retired"),
                    ("WORKFLOW_ASSIGNED", "Workflow assigned"),
                ],
                max_length=24,
            ),
        ),
    ]
